### ISSUE TITLE
Panic on errors

### ISSUE THREAD

**Issue by pkaeding** [Invoiced/invoiced-go#2]
It seems that there are many places in `connector.go` (and maybe elsewhere in the code) that panic when an error is encountered, instead of returning an error (which is more idiomatic in go).  This means that our application is unable to gracefully deal with errors and recover/retry.

**Comment by ppone** [comment]
Thanks will work on eliminating the panics.

**Comment by pkaeding** [comment]
Thanks for the quick fix!
