### ISSUE TITLE
Export `mockConnection`

### ISSUE THREAD

**Issue by shnewto** [Invoiced/invoiced-go#7]
Hey there! 
I'm wondering if you'd be willing to revise the un-exported function `mockConnection` in [mockconnection.go](https://github.com/Invoiced/invoiced-go/blob/master/mockconnection.go) to an exported `MockConnection`. I'd like to be able to mock connections for my own tests and as it stands I have to modify the package locally. 

I'd be happy to make a PR if you're okay with exposing the function but wanted to run it by y'all first.

**Comment by ppone** [comment]
Sure, I would be happy to review the PR
